plot_code <- list(
  scatter = 'ggplot(mtcars, aes(wt, mpg)) +\n  geom_point(aes(color = factor(cyl)), size = 3) +\n  geom_smooth(method = "lm", se = TRUE) +\n  labs(title = "Car Weight vs. MPG",\n       x = "Weight (1000 lbs)", y = "Miles per Gallon",\n       color = "Cylinders") +\n  theme_minimal(base_size = 18)',
  box = 'ggplot(diamonds, aes(cut, price)) +\n  geom_boxplot(aes(fill = cut)) +\n  labs(title = "Diamond Prices by Cut Quality",\n       x = "Cut", y = "Price (USD)") +\n  theme_minimal(base_size = 18)',
  density = 'ggplot(faithful, aes(waiting)) +\n  geom_density(aes(fill = "density"), alpha = 0.5) +\n  geom_histogram(aes(y = after_stat(density)), alpha = 0.3, bins = 30) +\n  labs(title = "Old Faithful Eruption Waiting Times",\n       x = "Waiting Time (minutes)", y = "Density") +\n  theme_minimal(base_size = 18) +\n  theme(legend.position = "none")',
  facet = 'ggplot(economics_long, aes(date, value)) +\n  geom_line() +\n  facet_wrap(~variable, scales = "free_y", ncol = 1) +\n  labs(title = "US Economic Time Series",\n       x = "Date", y = "Value") +\n  theme_minimal(base_size = 18)',
  bar = 'ggplot(mpg, aes(class)) +\n  geom_bar(aes(fill = drv)) +\n  labs(title = "Vehicle Class Distribution by Drive Type",\n       x = "Vehicle Class", y = "Count") +\n  theme_minimal(base_size = 18)',
  violin = 'ggplot(diamonds, aes(cut, price)) +\n  geom_violin(aes(fill = cut)) +\n  labs(title = "Diamond Price Distribution by Cut",\n       x = "Cut", y = "Price") +\n  theme_minimal(base_size = 18)',
  heatmap = 'diamonds %>%\n  count(cut, color) %>%\n  ggplot(aes(cut, color)) +\n  geom_tile(aes(fill = n)) +\n  scale_fill_viridis_c() +\n  labs(title = "Diamond Count by Cut and Color",\n       x = "Cut", y = "Color") +\n  theme_minimal(base_size = 18)',
  area = 'ggplot(economics, aes(date, unemploy)) +\n  geom_area(fill = "steelblue", alpha = 0.5) +\n  labs(title = "US Unemployment Over Time",\n       x = "Date", y = "Unemployment") +\n  theme_minimal(base_size = 18)',
  bubble = 'ggplot(mpg, aes(displ, hwy)) +\n  geom_point(aes(size = cty, color = class), alpha = 0.6) +\n  labs(title = "Engine Size vs. Highway MPG",\n       x = "Engine Displacement", y = "Highway MPG") +\n  theme_minimal(base_size = 18)',
  errorbar = 'diamonds %>%\n  group_by(cut) %>%\n  summarise(\n    mean_price = mean(price),\n    se = sd(price)/sqrt(n())\n  ) %>%\n  ggplot(aes(cut, mean_price)) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean_price - se, ymax = mean_price + se), width = 0.2) +\n  labs(title = "Mean Diamond Price by Cut (with SE)",\n       x = "Cut", y = "Mean Price") +\n  theme_minimal(base_size = 18)',
  beeswarm = 'ggplot(iris, aes(Species, Sepal.Length)) +\n  geom_beeswarm(aes(color = Species)) +\n  labs(title = "Iris Sepal Length Distribution",\n       subtitle = "Using ggbeeswarm") +\n  theme_minimal(base_size = 18)',
  bump = 'data <- data.frame(\n  year = rep(2015:2019, 5),\n  rank = c(1,1,2,3,1, 2,2,1,1,2, 3,3,3,2,3, 4,4,4,4,4, 5,5,5,5,5),\n  name = rep(c("A","B","C","D","E"), each=5)\n)\nggplot(data, aes(year, rank, color = name)) +\n  geom_bump() +\n  labs(title = "Rank Changes Over Time",\n       subtitle = "Using ggbump") +\n  theme_minimal(base_size = 18)',
  alluvial = 'data <- data.frame(\n  x = rep(c("Group A", "Group B"), each = 100),\n  y = rep(c("Type 1", "Type 2"), times = 100),\n  freq = sample(1:10, 200, replace = TRUE)\n)\nggplot(data, aes(axis1 = x, axis2 = y, y = freq)) +\n  geom_alluvium() +\n  geom_stratum() +\n  labs(title = "Flow Diagram",\n       subtitle = "Using ggalluvial") +\n  theme_minimal(base_size = 18)',
  ridges = 'ggplot(iris, aes(x = Sepal.Length, y = Species)) +\n  geom_density_ridges(aes(fill = Species)) +\n  labs(title = "Sepal Length Distribution by Species",\n       subtitle = "Using ggridges") +\n  theme_minimal(base_size = 18)',
  corrplot = 'corr <- cor(iris[, 1:4])\nggcorrplot(corr,\n           hc.order = TRUE,\n           type = "lower",\n           lab = TRUE) +\n  labs(title = "Correlation Matrix of Iris Features",\n       subtitle = "Using ggcorrplot") +\n  theme(text = element_text(size = 18))',
  mosaic = 'titanic_df <- as.data.frame(Titanic)\nggplot(data = titanic_df) +\n  geom_mosaic(aes(weight = Freq, x = product(Survived, Sex), fill = Class)) +\n  labs(title = "Titanic Survival by Sex and Class",\n       subtitle = "Using ggmosaic") +\n  theme_minimal(base_size = 18) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))',
  radar = 'data <- data.frame(\n  metric = c("Speed", "Power", "Agility", "Intelligence", "Strength"),\n  character1 = c(90, 80, 70, 60, 85),\n  character2 = c(70, 85, 90, 75, 65)\n)\nggradar(data,\n        values.radar = c(0, 50, 100),\n        grid.min = 0, grid.mid = 50, grid.max = 100) +\n  labs(title = "Character Attributes Comparison",\n       subtitle = "Using ggradar")',
  wordcloud = 'words <- data.frame(\n  word = c("R", "Shiny", "ggplot2", "Data", "Visualization", "Analysis",\n           "Statistics", "Programming", "Science", "Graphics"),\n  freq = sample(10:50, 10)\n)\nggplot(words, aes(label = word, size = freq)) +\n  geom_text_wordcloud() +\n  scale_size_area(max_size = 20) +\n  labs(title = "Word Cloud",\n       subtitle = "Using ggwordcloud") +\n  theme_minimal(base_size = 18)'
)


